version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run: apt-get update
      - run: apt-get -y install cmake make gcc
      - checkout
      - run: cmake --version
      - run: make --version
workflows:
    version: 2
    build_and_test:
      jobs:
        - build
